#!/usr/bin/env bash

# Device with Google Authenticator must have root [enable in Settings->System->Development options]
# Computer requires Android Developer Tools (adb)and SQLite 3.

# Connect your device in USB debugging mode.
$ adb root
$ adb pull /data/data/com.google.android.apps.authenticator2/databases/databases
$ sqlite3 ./databases "select * from accounts" > google_auth_database
$ rm ./databases

# Copy to password manager
