#!/bin/bash

# Hardcoded location of all org alternatives
loc="$HOME/.personal"

cur_org=`readlink $loc/org`
if [ "$?" -ne "0" ]; then
  echo "No current org, exiting..."
  exit 0
fi

unamestr=`uname`
if [[ "$unamestr" == "Darwin" ]]; then
  # Mac adds "/" at the end of readlink
  cur_org=`echo $cur_org | sed 's/\/$//'`
fi

emacs_pid=`pgrep emacs || pgrep Emacs`
if [ "$?" -ne "1" ]; then
    echo "Emacs process is running. Terminate first before switching..."
    exit 0
fi

if [ "$1" == "status" ] || [ "$1" == "st" ]; then
  if   [ "$cur_org" == "org_personal" ]; then echo 'Current status "personal"'
  elif [ "$cur_org" == "org_work" ];     then echo 'Current status "work"'
  else echo "Current status <unknown> ($cur_org)"; fi
  exit 0
fi

if   [ "$cur_org" == "org_personal" ]; then
  # personal -> work
  cd $loc
  rm -f $loc/org
  ln -s org_work org
  cd ..
  echo 'Switched to "work" mode'

elif [ "$cur_org" == "org_work" ]; then
  # work -> personal
  cd $loc
  rm -f org
  ln -s org_personal org
  cd ..
  echo 'Switched to "personal" mode'

else
  echo "Uknown current org \""$cur_org"\", exiting..."
fi
exit 0
