#!/bin/bash
host=`hostname`

if [[ "$host" != "geminga" ]]; then
    updatedb -l 0 -o ~/.locate.db -U ~/ \
        -e /home/prok/.kde4/share/apps/okular/docdata \
        -e /home/prok/.wine \
        -e /home/prok/.backup \
        -n .git
else
    updatedb -l 0 -o ~/.locate-home.db -U ~/ \
        -n ".git .kde .backup"
    updatedb -l 0 -o ~/.locate-data.db -U /data \
        -n ".git .kde .backup"
fi
